edition = "2021"
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
max_width = 100
tab_spaces = 4
hard_tabs = false
fn_single_line = false
fn_params_layout = "Vertical"
brace_style = "SameLineWhere"
struct_lit_single_line = false
trailing_comma = "Vertical"
reorder_impl_items = true
match_arm_blocks = true
match_block_trailing_comma = false
normalize_doc_attributes = true
normalize_comments = true
wrap_comments = true
comment_width = 80
reorder_imports = true
reorder_modules = true
overflow_delimited_expr = true
newline_style = "Unix"